use libp2p::futures::StreamExt;
use libp2p::identity::Keypair;
use libp2p::{
    PeerId, Swarm, kad, mdns, noise, request_response,
    swarm::{NetworkBehaviour, SwarmEvent},
    tcp, yamux,
};
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tokio::sync::mpsc;

use inference_engine::TensorState;

/// Network events generated by the P2P swarm and sent to the core engine/GUI.
#[derive(Debug, Clone)]
pub enum SwarmMessage {
    PeerConnected(PeerId),
    PeerDisconnected(PeerId),
    TensorReceived { from: PeerId, state: TensorState },
}

/// Commands sent from the core engine/GUI to the P2P network.
#[derive(Debug)]
pub enum Command {
    SendTensor { to: PeerId, state: TensorState },
    Dial(String),
}

/// A serialized wrapper over the tensor payload
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TensorRequest(pub TensorState);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TensorResponse(pub String); // Can return a simple ack or state

#[derive(NetworkBehaviour)]
pub struct SwarmNodeBehaviour {
    pub mdns: mdns::tokio::Behaviour,
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    pub request_response: request_response::cbor::Behaviour<TensorRequest, TensorResponse>,
}

pub struct NetworkTask {
    swarm: Swarm<SwarmNodeBehaviour>,
    cmd_rx: mpsc::Receiver<Command>,
    event_tx: mpsc::Sender<SwarmMessage>,
}

impl NetworkTask {
    pub fn new(
        cmd_rx: mpsc::Receiver<Command>,
        event_tx: mpsc::Sender<SwarmMessage>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let local_key = Keypair::generate_ed25519();
        let _local_peer_id = PeerId::from(local_key.public());

        // Setup transport
        let mut swarm = libp2p::SwarmBuilder::with_existing_identity(local_key)
            .with_tokio()
            .with_tcp(
                tcp::Config::default(),
                noise::Config::new,
                yamux::Config::default,
            )?
            .with_quic()
            .with_behaviour(|key| {
                let mdns = mdns::tokio::Behaviour::new(
                    mdns::Config::default(),
                    key.public().to_peer_id(),
                )?;

                let kademlia = kad::Behaviour::new(
                    key.public().to_peer_id(),
                    kad::store::MemoryStore::new(key.public().to_peer_id()),
                );

                let request_response = request_response::cbor::Behaviour::new(
                    [(
                        libp2p::StreamProtocol::new("/swarmnode/tensor/1.0.0"),
                        request_response::ProtocolSupport::Full,
                    )],
                    request_response::Config::default(),
                );

                Ok(SwarmNodeBehaviour {
                    mdns,
                    kademlia,
                    request_response,
                })
            })?
            .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_secs(60)))
            .build();

        // Listen on all interfaces
        swarm.listen_on("/ip4/0.0.0.0/tcp/0".parse()?)?;
        swarm.listen_on("/ip4/0.0.0.0/udp/0/quic-v1".parse()?)?;

        Ok(Self {
            swarm,
            cmd_rx,
            event_tx,
        })
    }

    pub async fn run(mut self) {
        loop {
            tokio::select! {
                cmd = self.cmd_rx.recv() => {
                    if let Some(command) = cmd {
                        self.handle_command(command).await;
                    } else {
                        break; // Channel closed
                    }
                }
                event = self.swarm.select_next_some() => {
                    self.handle_swarm_event(event).await;
                }
            }
        }
    }

    async fn handle_command(&mut self, cmd: Command) {
        match cmd {
            Command::SendTensor { to, state } => {
                let req = TensorRequest(state);
                self.swarm
                    .behaviour_mut()
                    .request_response
                    .send_request(&to, req);
            }
            Command::Dial(addr) => {
                if let Ok(multiaddr) = addr.parse::<libp2p::Multiaddr>() {
                    let _ = self.swarm.dial(multiaddr);
                }
            }
        }
    }

    async fn handle_swarm_event(&mut self, event: SwarmEvent<SwarmNodeBehaviourEvent>) {
        match event {
            SwarmEvent::NewListenAddr { address: _, .. } => {
                // E.g. println!("Listening on {:?}", address);
            }
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::Mdns(mdns::Event::Discovered(list))) => {
                for (peer_id, multiaddr) in list {
                    self.swarm
                        .behaviour_mut()
                        .kademlia
                        .add_address(&peer_id, multiaddr);
                    let _ = self
                        .event_tx
                        .send(SwarmMessage::PeerConnected(peer_id))
                        .await;
                }
            }
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::Mdns(mdns::Event::Expired(list))) => {
                for (peer_id, _) in list {
                    let _ = self
                        .event_tx
                        .send(SwarmMessage::PeerDisconnected(peer_id))
                        .await;
                }
            }
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::RequestResponse(
                request_response::Event::Message { peer, message },
            )) => {
                match message {
                    request_response::Message::Request {
                        request, channel, ..
                    } => {
                        // Received a tensor from a peer
                        let _ = self
                            .event_tx
                            .send(SwarmMessage::TensorReceived {
                                from: peer,
                                state: request.0,
                            })
                            .await;

                        // Acknowledge receipt
                        let _ = self
                            .swarm
                            .behaviour_mut()
                            .request_response
                            .send_response(channel, TensorResponse("ACK".into()));
                    }
                    request_response::Message::Response { .. } => {
                        // Peer acknowledged tensor receipt
                    }
                }
            }
            _ => {}
        }
    }
}
