use libp2p::futures::StreamExt;
use libp2p::identity::Keypair;
use libp2p::{
    PeerId, Swarm, kad, mdns, noise, request_response,
    swarm::{NetworkBehaviour, SwarmEvent},
    tcp, yamux,
};
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tokio::sync::mpsc;

use inference_engine::TensorState;

/// Network events generated by the P2P swarm and sent to the core engine/GUI.
#[derive(Debug, Clone)]
pub enum SwarmMessage {
    PeerConnected(PeerId),
    PeerDisconnected(PeerId),
    /// Received a partial computation from a peer
    ComputeResult {
        from: PeerId,
        state: TensorState,
    },
    /// Received a request from a peer to compute
    ComputeRequest {
        from: PeerId,
        state: TensorState,
        layers: usize,
    },
}

/// Commands sent from the core engine/GUI to the P2P network.
#[derive(Debug)]
pub enum Command {
    /// Request a remote peer to process N layers
    RouteCompute {
        to: PeerId,
        state: TensorState,
        layers: usize,
    },
    /// Send back the result of a computation
    SendResult {
        to: PeerId,
        state: TensorState,
    },
    Dial(String),
}

/// A serialized wrapper over the tensor payload
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TensorProtocolMsg {
    Request {
        state: TensorState,
        layers_to_process: usize,
    },
    Response {
        state: TensorState,
    },
}

#[derive(NetworkBehaviour)]
pub struct SwarmNodeBehaviour {
    pub mdns: mdns::tokio::Behaviour,
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    pub request_response: request_response::cbor::Behaviour<TensorProtocolMsg, TensorProtocolMsg>,
}

pub struct NetworkTask {
    swarm: Swarm<SwarmNodeBehaviour>,
    cmd_rx: mpsc::Receiver<Command>,
    event_tx: mpsc::Sender<SwarmMessage>,
}

impl NetworkTask {
    pub fn new(
        cmd_rx: mpsc::Receiver<Command>,
        event_tx: mpsc::Sender<SwarmMessage>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let local_key = Keypair::generate_ed25519();
        let _local_peer_id = PeerId::from(local_key.public());

        // Setup transport
        let mut swarm = libp2p::SwarmBuilder::with_existing_identity(local_key)
            .with_tokio()
            .with_tcp(
                tcp::Config::default(),
                noise::Config::new,
                yamux::Config::default,
            )?
            .with_quic()
            .with_behaviour(|key| {
                let mdns = mdns::tokio::Behaviour::new(
                    mdns::Config::default(),
                    key.public().to_peer_id(),
                )?;

                let kademlia = kad::Behaviour::new(
                    key.public().to_peer_id(),
                    kad::store::MemoryStore::new(key.public().to_peer_id()),
                );

                let request_response = request_response::cbor::Behaviour::new(
                    [(
                        libp2p::StreamProtocol::new("/swarmnode/tensor/2.0.0"),
                        request_response::ProtocolSupport::Full,
                    )],
                    request_response::Config::default(),
                );

                Ok(SwarmNodeBehaviour {
                    mdns,
                    kademlia,
                    request_response,
                })
            })?
            .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_secs(60)))
            .build();

        // Listen on all interfaces
        swarm.listen_on("/ip4/0.0.0.0/tcp/0".parse()?)?;
        swarm.listen_on("/ip4/0.0.0.0/udp/0/quic-v1".parse()?)?;

        Ok(Self {
            swarm,
            cmd_rx,
            event_tx,
        })
    }

    pub async fn run(mut self) {
        loop {
            tokio::select! {
                cmd = self.cmd_rx.recv() => {
                    if let Some(command) = cmd {
                        self.handle_command(command).await;
                    } else {
                        break; // Channel closed
                    }
                }
                event = self.swarm.select_next_some() => {
                    self.handle_swarm_event(event).await;
                }
            }
        }
    }

    async fn handle_command(&mut self, cmd: Command) {
        match cmd {
            Command::RouteCompute { to, state, layers } => {
                let req = TensorProtocolMsg::Request {
                    state,
                    layers_to_process: layers,
                };
                self.swarm
                    .behaviour_mut()
                    .request_response
                    .send_request(&to, req);
            }
            Command::SendResult { to: _, state: _ } => {
                // In a true request-response, the response is tied to the channel.
                // For simplicity in this architecture, we might route it back via a new request,
                // or just log it. The channel ID tracking would go here.
            }
            Command::Dial(addr) => {
                if let Ok(multiaddr) = addr.parse::<libp2p::Multiaddr>() {
                    let _ = self.swarm.dial(multiaddr);
                }
            }
        }
    }

    async fn handle_swarm_event(&mut self, event: SwarmEvent<SwarmNodeBehaviourEvent>) {
        match event {
            SwarmEvent::NewListenAddr { address: _, .. } => {}
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::Mdns(mdns::Event::Discovered(list))) => {
                for (peer_id, multiaddr) in list {
                    self.swarm
                        .behaviour_mut()
                        .kademlia
                        .add_address(&peer_id, multiaddr);
                    let _ = self
                        .event_tx
                        .send(SwarmMessage::PeerConnected(peer_id))
                        .await;
                }
            }
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::Mdns(mdns::Event::Expired(list))) => {
                for (peer_id, _) in list {
                    let _ = self
                        .event_tx
                        .send(SwarmMessage::PeerDisconnected(peer_id))
                        .await;
                }
            }
            SwarmEvent::Behaviour(SwarmNodeBehaviourEvent::RequestResponse(
                request_response::Event::Message { peer, message },
            )) => {
                match message {
                    request_response::Message::Request {
                        request, channel, ..
                    } => {
                        match request {
                            TensorProtocolMsg::Request {
                                state,
                                layers_to_process,
                            } => {
                                let _ = self
                                    .event_tx
                                    .send(SwarmMessage::ComputeRequest {
                                        from: peer,
                                        state,
                                        layers: layers_to_process,
                                    })
                                    .await;

                                // Dummy ACK response
                                let ack = TensorProtocolMsg::Response {
                                    state: TensorState {
                                        shape: vec![],
                                        data: vec![],
                                        current_layer: 0,
                                    },
                                };
                                let _ = self
                                    .swarm
                                    .behaviour_mut()
                                    .request_response
                                    .send_response(channel, ack);
                            }
                            TensorProtocolMsg::Response { state } => {
                                let _ = self
                                    .event_tx
                                    .send(SwarmMessage::ComputeResult { from: peer, state })
                                    .await;
                            }
                        }
                    }
                    request_response::Message::Response { response, .. } => {
                        if let TensorProtocolMsg::Response { state } = response {
                            let _ = self
                                .event_tx
                                .send(SwarmMessage::ComputeResult { from: peer, state })
                                .await;
                        }
                    }
                }
            }
            _ => {}
        }
    }
}
