jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release
      - name: Create Artifacts Directory
        run: |
          mkdir -p artifacts
      - name: Copy Build Outputs
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then \
            cp target/release/* artifacts/; \
          else \
            xcopy target\release\* artifacts\ /Y; \
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries-${{ matrix.os }}
          path: artifacts/