name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release
      - name: Create Artifacts Directory
        run: |
          mkdir -p artifacts
      - name: Copy Build Outputs
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then \n            cp target/release/* artifacts/; \n          else \n            xcopy target\release\* artifacts\ /Y; \n          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries-${{ matrix.os }}
          path: artifacts/